-- Replace the household invite code with expiring, single-use invitations.
--
-- The dropped column held a code generated by Math.random(), which never
-- expired and could be redeemed any number of times. Dropping it revokes every
-- code ever issued, which is the point: there is no way to tell which of them
-- are still written down somewhere.

CREATE TABLE "household_invites" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"household_id" uuid NOT NULL,
	"code_hash" text NOT NULL,
	"code_hint" text NOT NULL,
	"created_by" text NOT NULL,
	"label" text,
	"expires_at" timestamp NOT NULL,
	"used_at" timestamp,
	"used_by" text,
	"revoked_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "household_invites_code_hash_unique" UNIQUE("code_hash")
);
--> statement-breakpoint
CREATE TABLE "household_join_attempts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"clerk_id" text NOT NULL,
	"succeeded" boolean DEFAULT false NOT NULL,
	"attempted_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "households" DROP CONSTRAINT "households_invite_code_unique";--> statement-breakpoint
ALTER TABLE "household_invites" ADD CONSTRAINT "household_invites_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "household_invites_household_idx" ON "household_invites" USING btree ("household_id");--> statement-breakpoint
CREATE INDEX "household_join_attempts_clerk_idx" ON "household_join_attempts" USING btree ("clerk_id","attempted_at");--> statement-breakpoint
ALTER TABLE "households" DROP COLUMN "invite_code";
--> statement-breakpoint
-- Same reasoning as 0002: Supabase serves the public schema over PostgREST to
-- anyone holding the publishable key, which ships to the browser.
ALTER TABLE "household_invites" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "household_join_attempts" ENABLE ROW LEVEL SECURITY;
