"use client";

import { useState, useEffect } from "react";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport, isToolUIPart } from "ai";
import { MessageSquare, Send, Loader2, Bot, User, FileDown } from "lucide-react";
import { onChatRequest } from "@/lib/utils/chat-events";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useRef } from "react";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import { AI_DISCLAIMER } from "@/lib/constants";
import type { PortfolioAnalystUIMessage } from "@/lib/agents/portfolio-analyst";

const transport = new DefaultChatTransport({ api: "/api/chat" });

export function ChatPanel() {
  const [open, setOpen] = useState(false);
  const [input, setInput] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);

  const { messages, sendMessage, status, error } =
    useChat<PortfolioAnalystUIMessage>({ transport });

  const isActive = status === "streaming" || status === "submitted";

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, status]);

  // Listen for chat requests from other components (e.g., analysis cards)
  useEffect(() => {
    return onChatRequest((prompt) => {
      setOpen(true);
      if (prompt) {
        setTimeout(() => {
          sendMessage({ text: prompt });
        }, 100);
      }
    });
  }, [sendMessage]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isActive) return;
    sendMessage({ text: input.trim() });
    setInput("");
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(e);
    }
  };

  return (
    <>
      <Button
        size="icon"
        className="fixed bottom-6 right-6 z-50 h-14 w-14 rounded-full shadow-lg"
        onClick={() => setOpen(true)}
      >
        <MessageSquare className="h-6 w-6" />
        <span className="sr-only">Open AI Chat</span>
      </Button>

      <Sheet open={open} onOpenChange={setOpen}>
        <SheetContent
          side="right"
          className="flex w-full flex-col p-0 sm:max-w-lg"
        >
          <SheetHeader className="border-b px-4 py-3">
            <div className="flex items-center justify-between">
              <SheetTitle className="flex items-center gap-2">
                <Bot className="h-5 w-5 text-primary" />
                RetireWise AI
              </SheetTitle>
              {messages.length > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    // Extract text content from messages
                    const content = messages
                      .map((m) => {
                        const role = m.role === "user" ? "You" : "RetireWise AI";
                        const text = m.parts
                          .filter((p) => p.type === "text")
                          .map((p) => (p as { type: "text"; text: string }).text)
                          .join("\n");
                        return `${role}:\n${text}`;
                      })
                      .join("\n\n---\n\n");

                    const report = `RetireWise AI Analysis\n${new Date().toLocaleDateString()}\n${"=".repeat(50)}\n\n${content}\n\n${"=".repeat(50)}\nGenerated by RetireWise | For informational purposes only`;

                    // Use browser print to PDF
                    const printWindow = window.open("", "_blank");
                    if (printWindow) {
                      printWindow.document.write(`
                        <html>
                          <head>
                            <title>RetireWise AI Analysis</title>
                            <style>
                              body { font-family: -apple-system, system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1a1a1a; line-height: 1.6; }
                              h1 { font-size: 24px; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
                              .date { color: #666; font-size: 14px; }
                              .message { margin: 24px 0; }
                              .role { font-weight: 600; color: #6366f1; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
                              .content { white-space: pre-wrap; margin-top: 4px; }
                              hr { border: none; border-top: 1px solid #e5e7eb; margin: 16px 0; }
                              .footer { color: #999; font-size: 12px; margin-top: 40px; text-align: center; }
                            </style>
                          </head>
                          <body>
                            <h1>RetireWise AI Analysis</h1>
                            <p class="date">${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>
                            ${messages.map((m) => {
                              const role = m.role === "user" ? "You" : "RetireWise AI";
                              const text = m.parts
                                .filter((p) => p.type === "text")
                                .map((p) => (p as { type: "text"; text: string }).text)
                                .join("\n");
                              return `<div class="message"><div class="role">${role}</div><div class="content">${text.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div></div><hr/>`;
                            }).join("")}
                            <p class="footer">Generated by RetireWise &mdash; For informational purposes only</p>
                          </body>
                        </html>
                      `);
                      printWindow.document.close();
                      printWindow.print();
                    }
                  }}
                  className="text-xs"
                >
                  <FileDown className="mr-1.5 h-3.5 w-3.5" />
                  Save PDF
                </Button>
              )}
            </div>
          </SheetHeader>

          <div
            ref={scrollRef}
            className="flex-1 overflow-y-auto overscroll-contain px-4 -webkit-overflow-scrolling-touch"
            style={{ WebkitOverflowScrolling: "touch" }}
          >
            <div className="space-y-4 py-4">
              {messages.length === 0 && (
                <div className="flex flex-col items-center justify-center py-12 text-center">
                  <Bot className="mb-4 h-12 w-12 text-muted-foreground" />
                  <h3 className="font-semibold">Portfolio AI Assistant</h3>
                  <p className="mt-1 max-w-sm text-sm text-muted-foreground">
                    Ask me about your portfolio, allocation, performance, or get
                    rebalancing suggestions.
                  </p>
                  <div className="mt-4 flex flex-wrap justify-center gap-2">
                    {[
                      "Analyze my portfolio",
                      "Show allocation drift",
                      "What are my top holdings?",
                      "How diversified am I?",
                    ].map((suggestion) => (
                      <Button
                        key={suggestion}
                        variant="outline"
                        size="sm"
                        onClick={() => {
                          sendMessage({ text: suggestion });
                        }}
                      >
                        {suggestion}
                      </Button>
                    ))}
                  </div>
                </div>
              )}

              {messages.map((message) => (
                <div
                  key={message.id}
                  className={`flex gap-3 ${message.role === "user" ? "justify-end" : ""}`}
                >
                  {message.role === "assistant" && (
                    <div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10">
                      <Bot className="h-4 w-4 text-primary" />
                    </div>
                  )}
                  <div
                    className={`max-w-[85%] rounded-lg px-3 py-2 text-sm ${
                      message.role === "user"
                        ? "bg-primary text-primary-foreground"
                        : "bg-muted"
                    }`}
                  >
                    {message.parts.map((part, i) => {
                      if (part.type === "text") {
                        return (
                          <div
                            key={i}
                            className="whitespace-pre-wrap leading-relaxed"
                          >
                            {part.text}
                          </div>
                        );
                      }
                      if (isToolUIPart(part)) {
                        if (
                          part.state === "input-available" ||
                          part.state === "input-streaming"
                        ) {
                          return (
                            <div
                              key={i}
                              className="flex items-center gap-2 py-1 text-xs text-muted-foreground"
                            >
                              <Loader2 className="h-3 w-3 animate-spin" />
                              Analyzing...
                            </div>
                          );
                        }
                        if (part.state === "output-available") {
                          return (
                            <div key={i} className="py-1">
                              <Badge variant="secondary" className="text-xs">
                                Analysis complete
                              </Badge>
                            </div>
                          );
                        }
                      }
                      return null;
                    })}
                  </div>
                  {message.role === "user" && (
                    <div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary">
                      <User className="h-4 w-4 text-primary-foreground" />
                    </div>
                  )}
                </div>
              ))}

              {isActive && messages[messages.length - 1]?.role !== "assistant" && (
                <div className="flex gap-3">
                  <div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10">
                    <Bot className="h-4 w-4 text-primary" />
                  </div>
                  <div className="rounded-lg bg-muted px-3 py-2">
                    <Loader2 className="h-4 w-4 animate-spin" />
                  </div>
                </div>
              )}

              {error && (
                <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
                  Error: {error.message}
                </div>
              )}
            </div>
          </div>

          <div className="border-t p-4">
            <p className="mb-2 text-[10px] text-muted-foreground">
              {AI_DISCLAIMER}
            </p>
            <form onSubmit={handleSubmit} className="flex gap-2">
              <Textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Ask about your portfolio..."
                className="min-h-[44px] max-h-[120px] resize-none"
                rows={1}
              />
              <Button type="submit" size="icon" disabled={isActive || !input.trim()}>
                <Send className="h-4 w-4" />
              </Button>
            </form>
          </div>
        </SheetContent>
      </Sheet>
    </>
  );
}
